version: '3.8'

services:
  db: 
    image: postgres:17.2
    env_file: .env
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db_prod:/var/lib/postgresql/data

  bot:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - db
  
  migration:
    build: .
    env_file: .env
    depends_on:
      - db
      - bot
    command: alembic upgrade head

volumes:
  db_prod:
